### PR TITLE
Add .DS_Store to gitignore

### PR DESCRIPTION
**Pull request by philsmart**
Should be quick. So I will merge once I've spoken quickly to @iay back-channel.

### CODE REVIEW

**Comment by iay** [comment]
Fine to merge.

I would mention, however, that a cautious developer might consider using the `~/.gitignore_global` file to hold the names of random garbage that their local system has a tendency to generate. If you're not using that already (as a backstop) it's worth doing; you need to set it up in your `~/.gitconfig`.

**Comment by philsmart** [comment]
Ah, thanks. I do have that in `~/.gitignore_global` so I guess it must not be setup correctly in `~/.gitconfig`. I'll do that now.

**Comment by iay** [comment]
Mine has

```
[core]
        editor = code --wait --new-window
        excludesfile = ~/.gitignore_global
```

**Comment by philsmart** [comment]
Thanks. I was missing the core section and excludesfile.

**Pull request merged**
