### PR TITLE
Support development of new checks

### PR DESCRIPTION
**Pull request by iay**
Initial cut at a setup intended to allow
development of new checks and their
associated tests.

### CODE REVIEW

**Comment by iay** [comment]
This is as described in issue #101. I think it's complete but the only real way to validate that assertion is to try and use it to develop a new check. Any volunteers?

**Review by philsmart — COMMENTED** [review]
This exactly matches my understanding of what is described #101. I do have a quick question, but I will add that to #101.

**Review by philsmart — APPROVED** [review]

**Comment by iay** [comment]
For @alexstuart : if reviewing, worth reading the more explicit description of an expected process at https://github.com/ukf/ukf-testbed/issues/101#issuecomment-2520379841 first.

**Comment by alexstuart** [comment]
> For @alexstuart : if reviewing, worth reading the more explicit description of an expected process at [#101 (comment)](https://github.com/ukf/ukf-testbed/issues/101#issuecomment-2520379841) first.

The changes in the code look ok, and I agree that it is a complicated process for developing new checks.

**Review by alexstuart — APPROVED** [review]

**Pull request merged**
