### PR TITLE
106 add tests for checking empty nameidformat elements

### PR DESCRIPTION
**Pull request by philsmart**

### CODE REVIEW

**Comment by iay** [comment]
This looks fine, as far as it goes. I'd probably have done it slightly differently:

- The list of elements in `check_saml_strings` was in alphabetical order, and I would have retained that. It perhaps wasn't obvious.
- I might have committed the `validator-beans.xml` thing in two steps: the original, and the changed. Easier to review that way.

Obviously we won't land this branch in its current state, so I'm not going to "approve" it. But the next steps would probably be:

- Sync the production environment into its overlay here once it is updated (which may already be the case).
- Revise this branch to remove the `validator-beans.xml` commit or commits (which will involve removing the file, rebasing against `main`, testing and force-pushing).
- At that point just your original commit should remain and we can approve and land that.

**Review by iay — CHANGES_REQUESTED** [review]
See main comments.

**Comment by philsmart** [comment]
Thanks. 

For the location of the bean reference, I followed the production change in ukf-meta validation-beans.xml so they would be comparable. 

Yeah, I could have double-submitted validation-beans.xml. The first version would be identical to what it inherits, but it would make the upcoming fixes in the commits much more obvious (I'll do that next time).

**Comment by philsmart** [comment]
I've rebased the branch and removed the validation-beans.xml (as that is now in the ukf-metad-prod overlay)

**Review by iay — APPROVED** [review]

**Pull request merged**
