### PR TITLE
54 add tests for check shibboleth

### PR DESCRIPTION
**Pull request by philsmart**

### CODE REVIEW

**Comment by alexstuart** [comment]
Good catch of the 2 tests that need changing. 

Can you change the XSL so the different predicates are clearer? Something like this:

```
    <xsl:template match="md:SPSSODescriptor
        [contains(@protocolSupportEnumeration, 'urn:oasis:names:tc:SAML:2.0:protocol')]
        [md:NameIDFormat]
        [not(
          (md:NameIDFormat[.='urn:oasis:names:tc:SAML:2.0:nameid-format:persistent']) or 
          (md:NameIDFormat[.='urn:oasis:names:tc:SAML:2.0:nameid-format:transient'])
        )]">
```

**Comment by philsmart** [comment]
Sounds good. I will.

**Comment by philsmart** [comment]
That should be done for those predicates

**Review by iay — APPROVED** [review]
Looks good to me.

**Pull request merged**
