### PR TITLE
Add tests for ruleset check_mdrpi

### PR DESCRIPTION
**Pull request by philsmart**
Testing this is noisy, because the rest of the ruleset fails on numerous mdrpi element rules.

### CODE REVIEW

**Comment by iay** [comment]
I suggested doing this then the larger work associated with getting this ruleset working across the environments. I suppose the other option would be to do that latter work first instead, just omitting the unit tests around this bug, then adding this on to the end.

Your choice. Let me know when you have something you want me to review.

**Comment by philsmart** [comment]
OK. Let me reverse this by adding in the overall fix first.

**Comment by philsmart** [comment]
OK. I've re-ordered. You should be able to go through each commit to see different things failing and then being fixed. Of note, as soon as that ruleset is added (the first commit) the non-xalan validators will fail on elements in the other tests. So only on commit 77c8514ba480e4126595ab9dc77453db54080019 will things look clean (before I add the test that highlights the namespace prefix bug).

**Comment by iay** [comment]
Modulo the questions we discussed about cross-ruleset validity and schema validity in particular, I'm happy with this and will merge it.

**Pull request merged**
