### PR TITLE
Remove URLChecker tests, add stages, fix uncovered issue

### PR DESCRIPTION
**Pull request by philsmart**

### CODE REVIEW

**Comment by philsmart** [comment]
Ah. I think I have uncovered a load more errors than I thought.

**Comment by iay** [comment]
As mentioned in Slack, I have added the "value context" stuff to the MDA and rebuilt the 0.10 `md-validator` on top of that. If you rebuild your images, you should find this PR now failing but in an improved way. I suggest incorporating those changes and then we can have the discussion with @alexstuart about whether we're at "good enough" or need additional changes.

**Comment by philsmart** [comment]
I see these new changes. I will update the PR.

**Comment by philsmart** [comment]
I've updated the PR with the new, and certainly improved, error messages. As @iay already commented, the XSLT variants also include the name of the erroneous XML element, but it should be clear from the label of the test (filename etc) what is producing the error.

**Review by iay — APPROVED** [review]

**Pull request merged**
